### ISSUE TITLE
Default metallicity should be set to 0 for the by-eye check

### ISSUE THREAD

**Issue by ctheissen** [BU-hammerTeam/PyHammer#2] opened 2016-08-13 06:00 UTC
The widest spectral template coverage is for [Fe/H] = 0 (or close to zero), so it makes sense for this to be the starting value.

**Comment by zephyr5050** [comment] 2016-08-13 06:49
Do you not think the default metallicity on the eyecheck should be what the guessing algorithm determined?

**Comment by westukiah** [comment] 2016-08-13 15:06
I like using the best guess just like for the spectral type

**Comment by ctheissen** [comment] 2016-08-13 15:23
I didn't realize it was supposed to default to the best guess. For all my spectra it defaulted to the same thing, which was a G0 with a metalizing of -1.5. I just thought this was the default. Sounds like there's something else going on. 

Is it only comparing the region of my spectrum, out the entire region of the template? I think the plotting should only show the region of overlap, not the regions without overlap between the template and the input spectrum.

**Comment by zephyr5050** [comment] 2016-08-13 15:53
Can you email me a few of your spectra? We've only really started the testing phase of this so I'm sure there's plenty of setups and cases we haven't tested yet. I'll take a look at what's going on with your spectra and see what can be done for them.

**Comment by zephyr5050** [comment] 2016-09-07 21:45
Closing this issue. The original issue turned out to be caused by something else which are working to resolve.

**Closed by zephyr5050** 2016-09-07 21:45 UTC
